# Generated by Django 3.0.6 on 2020-06-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('voteAverage', models.FloatField(default=0)),
                ('poster', models.ImageField(upload_to='')),
                ('slug', models.SlugField()),
                ('released_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('released_date', models.DateTimeField(auto_now_add=True)),
                ('thumb', models.ImageField(upload_to='')),
                ('animeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('timeDuration', models.TimeField()),
                ('episodeID', models.IntegerField()),
                ('local_path', models.TextField()),
                ('thumb', models.ImageField(upload_to='')),
                ('released_date', models.DateTimeField(auto_now_add=True)),
                ('seasonID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.Season')),
            ],
        ),
    ]
